### ISSUE TITLE
Systematic crashes: bad initial setup?

### ISSUE THREAD

**Issue by YaZko** [madjar/nox#46]
Hi guys,

I just installed nixos on my machine and have an issue with nox. Long story short, any use of it returns the error whose Traceback is at the end of this message. 
What I suspect to be responsible for the problem is my eagerness: I installed nox asap, as root, before creating my user account. Nox worked at this time. Then, logged as a user, I tried to use it and got this error. I tried to install it as a user, still got the error. Relogged as root, uninstalled it as root (a simple nix-env --uninstall nox if that matters), relloged back as user but still get the error.

Would anyone know what the problem might be and how to fix it?

Thanks,
Best,
Yannick.

Traceback (most recent call last):
  File "/nix/store/hsp1gm11s4nwx276ddn87f2m590qikca-nox-0.0.2/bin/.nox-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/hsp1gm11s4nwx276ddn87f2m590qikca-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 56, in main
    results = [p for p in all_packages()
  File "/nix/store/hsp1gm11s4nwx276ddn87f2m590qikca-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 46, in all_packages
    packages_json = region.get_or_create(key, nix_packages_json)
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/nix/store/sflvgz4h7q2s5xlijls6vqpl8q7wlj34-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/nix/store/sflvgz4h7q2s5xlijls6vqpl8q7wlj34-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/nix/store/sflvgz4h7q2s5xlijls6vqpl8q7wlj34-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 128, in _enter_create
    self.mutex.acquire()
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/util.py", line 172, in acquire
    elif self.mutex.acquire(wait=wait):
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 303, in acquire
    return self.acquire_write_lock(wait)
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 405, in acquire_write_lock
    return self._acquire(wait, os.O_WRONLY, self._module.LOCK_EX)
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 415, in _acquire
    fileno = os.open(self.filename, wrflag)
PermissionError: [Errno 13] Permission denied: '/tmp/nox.dbm.dogpile.lock'

**Comment by madjar** [comment]
Hello !

Sorry about this, it's a bug about using nox with multiple users that was fixed in #39, but the fix is not released. I'll try to do this when I have the time.

You can work around it for now by deleting `/tmp/nox.dbm.dogpile.lock` as root.

**Comment by YaZko** [comment]
Hi ! Thanks a lot for the prompt answer. 

Deleting dogpile.lock did not fix the issue, permission was then denied for /tmp/nox.dbm.rw.lock which I also deleted. It now fails with:

Traceback (most recent call last):
  File "/nix/store/hsp1gm11s4nwx276ddn87f2m590qikca-nox-0.0.2/bin/.nox-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/g7ad1dhzac91zvcksq90mc7hjbkx92vw-python3.4-click-6.3/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/hsp1gm11s4nwx276ddn87f2m590qikca-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 56, in main
    results = [p for p in all_packages()
  File "/nix/store/hsp1gm11s4nwx276ddn87f2m590qikca-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 46, in all_packages
    packages_json = region.get_or_create(key, nix_packages_json)
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/nix/store/sflvgz4h7q2s5xlijls6vqpl8q7wlj34-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/nix/store/sflvgz4h7q2s5xlijls6vqpl8q7wlj34-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/nix/store/sflvgz4h7q2s5xlijls6vqpl8q7wlj34-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 617, in gen_value
    self.backend.set(key, value)
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 235, in set
    with self._dbm_file(True) as dbm:
  File "/nix/store/gsypv0i47cz4vd1cinjqb73za094hdyy-python3-3.4.4/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/nix/store/kvm8f64qz7jzj4inkk3qkfxpqayj0n50-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 213, in _dbm_file
    "w" if write else "r")
  File "/nix/store/gsypv0i47cz4vd1cinjqb73za094hdyy-python3-3.4.4/lib/python3.4/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 13] Permission denied

**Comment by madjar** [comment]
Oh, sorry, my mistake. Delete everything that starts with `nox` in `/tmp`, that should do the trick.

**Comment by YaZko** [comment]
It definitively did, perfect! Sorry I should have guessed this by myself but did not want to accidentally delete relevant stuff.
Thanks again for the help!
